name: Create Release

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    build:
        name: Release in Github
        runs-on: ubuntu-latest
        steps:
            - name: Get version from tag
              id: tag_name
              run: |
                  echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
              shell: bash
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Get Changelog Entry
              id: changelog_reader
              uses: artlaman/conventional-changelog-reader-action@v1.1.0
              with:
                  version: ${{ steps.tag_name.outputs.current_version }}
                  path: ./CHANGELOG.md
            - name: Create/update release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ steps.changelog_reader.outputs.version }}
                  name: Release ${{ steps.changelog_reader.outputs.version }}
                  body: ${{ steps.changelog_reader.outputs.changes }}
                  prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
                  allowUpdates: true
                  token: ${{ secrets.GITHUB_TOKEN }}
